services:
  - type: web
    name: tiktokshop
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    region: singapore
    envVars:
      - key: NODE_ENV
        value: production
