services:
  - type: web
    name: tiktokshop-admin
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    autoDeploy: true
    healthCheckPath: /
    domains:
      - tiktokshop888.com
