services:
  - type: web
    name: tiktokshop
    env: node
    region: singapore
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      NODE_ENV: production
