name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"  # Chạy mỗi 10 phút
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App (Main Domain)
        run: |
          echo "🔄 Đang ping trang chính Render..."
          # Ping domain chính của bạn
          curl -s -o /dev/null -w "%{http_code}" https://tiktokshop888.com/
          echo "✅ Ping thành công!"
